#server:
#  port: 8080
#spring:
#  datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#      username: root
#      password: root
#  mybatis:
#    type-aliases-package: com.vuetest.pojo
#    mapper-locations: classpath:/mapper/*.xml
#
